# Generated by Django 5.1.4 on 2024-12-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_userquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('text_body', models.CharField(blank=True, max_length=4000)),
                ('user_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userquestion')),
            ],
        ),
    ]
