# Generated by Django 5.1.4 on 2024-12-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geminiai',
            name='text_body',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='geminiai',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
